# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import player_stats_update_pb2 as player__stats__update__pb2


class PlayerStatsUpdaterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdatePlayerStats = channel.unary_unary(
                '/pyvalor.PlayerStatsUpdater/UpdatePlayerStats',
                request_serializer=player__stats__update__pb2.Request.SerializeToString,
                response_deserializer=player__stats__update__pb2.Response.FromString,
                )


class PlayerStatsUpdaterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdatePlayerStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayerStatsUpdaterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdatePlayerStats': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlayerStats,
                    request_deserializer=player__stats__update__pb2.Request.FromString,
                    response_serializer=player__stats__update__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pyvalor.PlayerStatsUpdater', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PlayerStatsUpdater(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdatePlayerStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pyvalor.PlayerStatsUpdater/UpdatePlayerStats',
            player__stats__update__pb2.Request.SerializeToString,
            player__stats__update__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
