# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_stats_update.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19player_stats_update.proto\x12\x07pyvalor\"\x1e\n\x07Request\x12\x13\n\x0bplayer_uuid\x18\x01 \x03(\t\"\x1c\n\x08Response\x12\x10\n\x08\x66\x61ilures\x18\x01 \x03(\t2P\n\x12PlayerStatsUpdater\x12:\n\x11UpdatePlayerStats\x12\x10.pyvalor.Request\x1a\x11.pyvalor.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'player_stats_update_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=38
  _globals['_REQUEST']._serialized_end=68
  _globals['_RESPONSE']._serialized_start=70
  _globals['_RESPONSE']._serialized_end=98
  _globals['_PLAYERSTATSUPDATER']._serialized_start=100
  _globals['_PLAYERSTATSUPDATER']._serialized_end=180
# @@protoc_insertion_point(module_scope)
