LEFT_PAGE_EMOJI = '⬅️'
RIGHT_PAGE_EMOJI = '➡️'

COUNTRY_TO_CURRENCY = {"BD": "BDT", "BE": "EUR", "BF": "XOF", "BG": "BGN", "BA": "BAM", "BB": "BBD", "WF": "XPF", "BL": "EUR", "BM": "BMD", "BN": "BND", "BO": "BOB", "BH": "BHD", "BI": "BIF", "BJ": "XOF", "BT": "BTN", "JM": "JMD", "BV": "NOK", "BW": "BWP", "WS": "WST", "BQ": "USD", "BR": "BRL", "BS": "BSD", "JE": "GBP", "BY": "BYR", "BZ": "BZD", "RU": "RUB", "RW": "RWF", "RS": "RSD", "TL": "USD", "RE": "EUR", "TM": "TMT", "TJ": "TJS", "RO": "RON", "TK": "NZD", "GW": "XOF", "GU": "USD", "GT": "GTQ", "GS": "GBP", "GR": "EUR", "GQ": "XAF", "GP": "EUR", "JP": "JPY", "GY": "GYD", "GG": "GBP", "GF": "EUR", "GE": "GEL", "GD": "XCD", "GB": "GBP", "GA": "XAF", "SV": "USD", "GN": "GNF", "GM": "GMD", "GL": "DKK", "GI": "GIP", "GH": "GHS", "OM": "OMR", "TN": "TND", "JO": "JOD", "HR": "HRK", "HT": "HTG", "HU": "HUF", "HK": "HKD", "HN": "HNL", "HM": "AUD", "VE": "VEF", "PR": "USD", "PS": "ILS", "PW": "USD", "PT": "EUR", "SJ": "NOK", "PY": "PYG", "IQ": "IQD", "PA": "PAB", "PF": "XPF", "PG": "PGK", "PE": "PEN", "PK": "PKR", "PH": "PHP", "PN": "NZD", "PL": "PLN", "PM": "EUR", "ZM": "ZMK", "EH": "MAD", "EE": "EUR", "EG": "EGP", "ZA": "ZAR", "EC": "USD", "IT": "EUR", "VN": "VND", "SB": "SBD", "ET": "ETB", "SO": "SOS", "ZW": "ZWL", "SA": "SAR", "ES": "EUR", "ER": "ERN", "ME": "EUR", "MD": "MDL", "MG": "MGA", "MF": "EUR", "MA": "MAD", "MC": "EUR", "UZ": "UZS", "MM": "MMK", "ML": "XOF", "MO": "MOP", "MN": "MNT", "MH": "USD", "MK": "MKD", "MU": "MUR", "MT": "EUR", "MW": "MWK", "MV": "MVR", "MQ": "EUR", "MP": "USD", "MS": "XCD", "MR": "MRO", "IM": "GBP", "UG": "UGX", "TZ": "TZS", "MY": "MYR", "MX": "MXN", "IL": "ILS", "FR": "EUR", "IO": "USD", "SH": "SHP", "FI": "EUR", "FJ": "FJD", "FK": "FKP", "FM": "USD", "FO": "DKK", "NI": "NIO", "NL": "EUR", "NO": "NOK", "NA": "NAD", "VU": "VUV", "NC": "XPF", "NE": "XOF", "NF": "AUD", "NG": "NGN", "NZ": "NZD", "NP": "NPR", "NR": "AUD", "NU": "NZD", "CK": "NZD", "XK": "EUR", "CI": "XOF", "CH": "CHF", "CO": "COP", "CN": "CNY", "CM": "XAF", "CL": "CLP", "CC": "AUD", "CA": "CAD", "CG": "XAF", "CF": "XAF", "CD": "CDF", "CZ": "CZK", "CY": "EUR", "CX": "AUD", "CR": "CRC", "CW": "ANG", "CV": "CVE", "CU": "CUP", "SZ": "SZL", "SY": "SYP", "SX": "ANG", "KG": "KGS", "KE": "KES", "SS": "SSP", "SR": "SRD", "KI": "AUD", "KH": "KHR", "KN": "XCD", "KM": "KMF", "ST": "STD", "SK": "EUR", "KR": "KRW", "SI": "EUR", "KP": "KPW", "KW": "KWD", "SN": "XOF", "SM": "EUR", "SL": "SLL", "SC": "SCR", "KZ": "KZT", "KY": "KYD", "SG": "SGD", "SE": "SEK", "SD": "SDG", "DO": "DOP", "DM": "XCD", "DJ": "DJF", "DK": "DKK", "VG": "USD", "DE": "EUR", "YE": "YER", "DZ": "DZD", "US": "USD", "UY": "UYU", "YT": "EUR", "UM": "USD", "LB": "LBP", "LC": "XCD", "LA": "LAK", "TV": "AUD", "TW": "TWD", "TT": "TTD", "TR": "TRY", "LK": "LKR", "LI": "CHF", "LV": "EUR", "TO": "TOP", "LT": "LTL", "LU": "EUR", "LR": "LRD", "LS": "LSL", "TH": "THB", "TF": "EUR", "TG": "XOF", "TD": "XAF", "TC": "USD", "LY": "LYD", "VA": "EUR", "VC": "XCD", "AE": "AED", "AD": "EUR", "AG": "XCD", "AF": "AFN", "AI": "XCD", "VI": "USD", "IS": "ISK", "IR": "IRR", "AM": "AMD", "AL": "ALL", "AO": "AOA", "AQ": "", "AS": "USD", "AR": "ARS", "AU": "AUD", "AT": "EUR", "AW": "AWG", "IN": "INR", "AX": "EUR", "AZ": "AZN", "IE": "EUR", "ID": "IDR", "UA": "UAH", "QA": "QAR", "MZ": "MZN"}
COUNTRY_NAMES = {"BD": "Bangladesh", "BE": "Belgium", "BF": "Burkina Faso", "BG": "Bulgaria", "BA": "Bosnia and Herzegovina", "BB": "Barbados", "WF": "Wallis and Futuna", "BL": "Saint Barthelemy", "BM": "Bermuda", "BN": "Brunei", "BO": "Bolivia", "BH": "Bahrain", "BI": "Burundi", "BJ": "Benin", "BT": "Bhutan", "JM": "Jamaica", "BV": "Bouvet Island", "BW": "Botswana", "WS": "Samoa", "BQ": "Bonaire, Saint Eustatius and Saba ", "BR": "Brazil", "BS": "Bahamas", "JE": "Jersey", "BY": "Belarus", "BZ": "Belize", "RU": "Russia", "RW": "Rwanda", "RS": "Serbia", "TL": "East Timor", "RE": "Reunion", "TM": "Turkmenistan", "TJ": "Tajikistan", "RO": "Romania", "TK": "Tokelau", "GW": "Guinea-Bissau", "GU": "Guam", "GT": "Guatemala", "GS": "South Georgia and the South Sandwich Islands", "GR": "Greece", "GQ": "Equatorial Guinea", "GP": "Guadeloupe", "JP": "Japan", "GY": "Guyana", "GG": "Guernsey", "GF": "French Guiana", "GE": "Georgia", "GD": "Grenada", "GB": "United Kingdom", "GA": "Gabon", "SV": "El Salvador", "GN": "Guinea", "GM": "Gambia", "GL": "Greenland", "GI": "Gibraltar", "GH": "Ghana", "OM": "Oman", "TN": "Tunisia", "JO": "Jordan", "HR": "Croatia", "HT": "Haiti", "HU": "Hungary", "HK": "Hong Kong", "HN": "Honduras", "HM": "Heard Island and McDonald Islands", "VE": "Venezuela", "PR": "Puerto Rico", "PS": "Palestinian Territory", "PW": "Palau", "PT": "Portugal", "SJ": "Svalbard and Jan Mayen", "PY": "Paraguay", "IQ": "Iraq", "PA": "Panama", "PF": "French Polynesia", "PG": "Papua New Guinea", "PE": "Peru", "PK": "Pakistan", "PH": "Philippines", "PN": "Pitcairn", "PL": "Poland", "PM": "Saint Pierre and Miquelon", "ZM": "Zambia", "EH": "Western Sahara", "EE": "Estonia", "EG": "Egypt", "ZA": "South Africa", "EC": "Ecuador", "IT": "Italy", "VN": "Vietnam", "SB": "Solomon Islands", "ET": "Ethiopia", "SO": "Somalia", "ZW": "Zimbabwe", "SA": "Saudi Arabia", "ES": "Spain", "ER": "Eritrea", "ME": "Montenegro", "MD": "Moldova", "MG": "Madagascar", "MF": "Saint Martin", "MA": "Morocco", "MC": "Monaco", "UZ": "Uzbekistan", "MM": "Myanmar", "ML": "Mali", "MO": "Macao", "MN": "Mongolia", "MH": "Marshall Islands", "MK": "Macedonia", "MU": "Mauritius", "MT": "Malta", "MW": "Malawi", "MV": "Maldives", "MQ": "Martinique", "MP": "Northern Mariana Islands", "MS": "Montserrat", "MR": "Mauritania", "IM": "Isle of Man", "UG": "Uganda", "TZ": "Tanzania", "MY": "Malaysia", "MX": "Mexico", "IL": "Israel", "FR": "France", "IO": "British Indian Ocean Territory", "SH": "Saint Helena", "FI": "Finland", "FJ": "Fiji", "FK": "Falkland Islands", "FM": "Micronesia", "FO": "Faroe Islands", "NI": "Nicaragua", "NL": "Netherlands", "NO": "Norway", "NA": "Namibia", "VU": "Vanuatu", "NC": "New Caledonia", "NE": "Niger", "NF": "Norfolk Island", "NG": "Nigeria", "NZ": "New Zealand", "NP": "Nepal", "NR": "Nauru", "NU": "Niue", "CK": "Cook Islands", "XK": "Kosovo", "CI": "Ivory Coast", "CH": "Switzerland", "CO": "Colombia", "CN": "China", "CM": "Cameroon", "CL": "Chile", "CC": "Cocos Islands", "CA": "Canada", "CG": "Republic of the Congo", "CF": "Central African Republic", "CD": "Democratic Republic of the Congo", "CZ": "Czech Republic", "CY": "Cyprus", "CX": "Christmas Island", "CR": "Costa Rica", "CW": "Curacao", "CV": "Cape Verde", "CU": "Cuba", "SZ": "Swaziland", "SY": "Syria", "SX": "Sint Maarten", "KG": "Kyrgyzstan", "KE": "Kenya", "SS": "South Sudan", "SR": "Suriname", "KI": "Kiribati", "KH": "Cambodia", "KN": "Saint Kitts and Nevis", "KM": "Comoros", "ST": "Sao Tome and Principe", "SK": "Slovakia", "KR": "South Korea", "SI": "Slovenia", "KP": "North Korea", "KW": "Kuwait", "SN": "Senegal", "SM": "San Marino", "SL": "Sierra Leone", "SC": "Seychelles", "KZ": "Kazakhstan", "KY": "Cayman Islands", "SG": "Singapore", "SE": "Sweden", "SD": "Sudan", "DO": "Dominican Republic", "DM": "Dominica", "DJ": "Djibouti", "DK": "Denmark", "VG": "British Virgin Islands", "DE": "Germany", "YE": "Yemen", "DZ": "Algeria", "US": "United States", "UY": "Uruguay", "YT": "Mayotte", "UM": "United States Minor Outlying Islands", "LB": "Lebanon", "LC": "Saint Lucia", "LA": "Laos", "TV": "Tuvalu", "TW": "Taiwan", "TT": "Trinidad and Tobago", "TR": "Turkey", "LK": "Sri Lanka", "LI": "Liechtenstein", "LV": "Latvia", "TO": "Tonga", "LT": "Lithuania", "LU": "Luxembourg", "LR": "Liberia", "LS": "Lesotho", "TH": "Thailand", "TF": "French Southern Territories", "TG": "Togo", "TD": "Chad", "TC": "Turks and Caicos Islands", "LY": "Libya", "VA": "Vatican", "VC": "Saint Vincent and the Grenadines", "AE": "United Arab Emirates", "AD": "Andorra", "AG": "Antigua and Barbuda", "AF": "Afghanistan", "AI": "Anguilla", "VI": "U.S. Virgin Islands", "IS": "Iceland", "IR": "Iran", "AM": "Armenia", "AL": "Albania", "AO": "Angola", "AQ": "Antarctica", "AS": "American Samoa", "AR": "Argentina", "AU": "Australia", "AT": "Austria", "AW": "Aruba", "IN": "India", "AX": "Aland Islands", "AZ": "Azerbaijan", "IE": "Ireland", "ID": "Indonesia", "UA": "Ukraine", "QA": "Qatar", "MZ": "Mozambique"}

CURRENCY_CODES = [[v, COUNTRY_NAMES[k]] for k, v in COUNTRY_TO_CURRENCY.items()]

ITEM_TO_EMOJI_MAP = {
    "Resonance": "relikbasicGold",
    "Convergence": "spearmulti3",
    "Labyrinth": "bowearth3",
    "Trance": "wandfire3",
    "Bloodbath": "spearearth3",
    "Quetzalcoatl": "wandair3",
    "Hanafubuki": "daggerair3",
    "Epoch": "bowbasicGold",
    "Oblivion": "daggermulti3",
    "Immolation": "relikfire3",
    "Warp": "wandair3",
    "Singularity": "wandmulti3",
    "Fatal": "wandthunder3",
    "Stratiformis": "bowair3",
    "Revenant": "diamondboots",
    "Warchief": "diamondboots",
    "Spring": "bowwater3",
    "Monster": "wandfire3",
    "Nirvana": "daggerwater3",
    "Absolution": "relikfire3",
    "Divzer": "bowthunder3",
    "Collapse": "spearmulti3",
    "Stardew": "diamondboots",
    "Cataclysm": "daggerthunder3",
    "Gaia": "wandearth3",
    "Weathered": "daggerair3",
    "Lament": "wandwater3",
    "Thrundacrack": "spearthunder3",
    "Fantasia": "relikmulti3",
    "Grimtrap": "daggerearth3",
    "Dawnbreak": "diamondboots",
    "Toxoplasmosis": "relikearth3",
    "Grandmother": "bowearth3",
    "Idol": "spearwater3",
    "Moontower": "diamondboots",
    "Ignis": "bowfire3",
    "Nullification": "daggerbasicGold",
    "Sunstar": "relikthunder3",
    "Slayer": "diamondboots",
    "Hadal": "relikwater3",
    "Alkatraz": "spearearth1",
    "Boreal": "diamondboots",
    "Guardian": "spearfire3",
    "Olympic": "relikair3",
    "Freedom": "bowmulti3",
    "Galleon": "diamondboots",
    "Resurgence": "diamondboots",
    "Hero": "spearair3",
    "Crusade Sabatons": "diamondboots",
    "Discoverer": "diamondchestplate",
    "Apocalypse": "spearfire3",
    "Aftershock": "relikearth3",
    "Az": "bowthunder3",
    "Archangel": "spearair3",
    "Pure": "wandmulti1",
    "Corkian Insulator": "corkianinsulator", 
    "Corkian Simulator": "corkiansimulator",
    "Inferno": "daggerfire3"
}

EMOJIS = {
    "shiny": "<:shiny:1373802935628075078>",
    "bowbasicGold": "<:bowbasicGold:1373920955470053417>",
    "bowair3": "<:bowair3:1373921980797030410>",
    "bowearth3": "<:bowearth3:1373920043665985557>",
    "bowfire3": "<:bowfire3:1373925207785472010>",
    "bowmulti3": "<:bowmulti3:1373926837822160916>",
    "bowthunder3": "<:bowthunder3:1373923404457050172>",
    "bowwater3": "<:bowwater3:1373922333579939930>",
    "daggerbasicGold": "<:daggerbasicGold:1373925389692567562>",
    "daggerair3": "<:daggerair3:1373920767846252655>",
    "daggerearth3": "<:daggerearth3:1373924665252122676>",
    "daggerfire3": "<:daggerfire3:1373935301243699210>",
    "daggermulti3": "<:daggermulti3:1373921096436289599>",
    "daggerthunder3": "<:daggerthunder3:1373923825963499560>",
    "daggerwater3": "<:daggerwater3:1373923164895313940>",
    "relikbasicGold": "<:relikbasicGold:1373919402348646421>",
    "relikair3": "<:relikair3:1373926721631293602>",
    "relikearth3": "<:relikearth3:1373924845590675526>",
    "relikfire3": "<:relikfire3:1373921291874078750>",
    "relikmulti3": "<:relikmulti3:1373924542543691796>",
    "relikthunder3": "<:relikthunder3:1373925496286478377>",
    "relikwater3": "<:relikwater3:1373925806866432032>",
    "spearair3": "<:spearair3:1373926998249967706>",
    "spearearth1": "<:spearearth1:1373925986835496971>",
    "spearearth3": "<:spearearth3:1373920380972040214>",
    "spearfire3": "<:spearfire3:1373926172160950324>",
    "spearmulti3": "<:spearmulti3:1373919685690527744>",
    "spearthunder3": "<:spearthunder3:1373924419453587496>",
    "spearwater3": "<:spearwater3:1373925043993706537>",
    "wandair3": "<:wandair3:1373920550220595200>",
    "wandearth3": "<:wandearth3:1373924039063634020>",
    "wandfire3": "<:wandfire3:1373920184170971157>",
    "wandmulti1": "<:wandmulti1:1373927744290947132>",
    "wandmulti3": "<:wandmulti3:1373921553065971742>",
    "wandthunder3": "<:wandthunder3:1373921813716930633>",
    "wandwater3": "<:wandwater3:1373924251404472350>",
    "diamondchestplate": "<:diamondchestplate:1373927161433686027>",
    "diamondboots": "<:diamondboots:1373922078608199731>",
    "corkianinsulator": "<:corkianinsulator:1373934409597583400>",
    "corkiansimulator": "<:corkiansimulator:1373934436374282271>"
}
